import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/ui-root/Header";
import "./globals.css";
import { Topic } from "@/types/topic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const res = await fetch("http://localhost:3000/api/topics", {
    next: { revalidate: 60 }
  });

  const topics: Topic[] = await res.json();
console.log(topics);
  return (
    <html lang="en">
      <body>
        <Header topics={topics} />
        {children}
      </body>
    </html>
  );
}
